language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: ENV_QTC_SOURCE="$TRAVIS_BUILD_DIR/qt-creator-opensource-src-3.6.0" ENV_QTC_BUILD="$TRAVIS_BUILD_DIR/qtc_build/3.6.0/lib/qtcreator/" ENV_QTC_VERSION="3.6.0" ENV_QTC_MV="6"
    - os: osx
      compiler: clang
      env: ENV_QTC_SOURCE="$TRAVIS_BUILD_DIR/qt-creator-opensource-src-3.6.0" ENV_QTC_BUILD="$TRAVIS_BUILD_DIR/qtc_build/3.6.0/" ENV_QTC_VERSION="3.6.0" ENV_QTC_MV="6" 

env:
  global:
    - VERSION=1.0

before_install:
  - sudo build/before_install.sh

install:
  - sudo build/install.sh

before_script:
  - git submodule update --init

script:
  - mkdir -p build && cd build
  - export PLUGIN_OUT_PATH="$(pwd)/plugins/${ENV_QTC_VERSION}/"
  - mkdir -p "${PLUGIN_OUT_PATH}"
  - qmake ../dubprojectmanager.pro -r CONFIG+=release QTC_SOURCE="${ENV_QTC_SOURCE}" QTC_BUILD="${ENV_QTC_BUILD}" OUTPUT_PATH="${PLUGIN_OUT_PATH}" SET_VERSION_MINOR="${ENV_QTC_MV}"
  - make
  - find "$TRAVIS_BUILD_DIR/build/plugins"

addons:
  artifacts:
    paths:
      - ./build/plugins

before_deploy:
  - f [[ $TRAVIS_OS_NAME == 'osx' ]]; then "$TRAVIS_BUILD_DIR/build/fix_mac.sh" "$TRAVIS_BUILD_DIR"/build/plugins/*.dylib ; fi
  - python "$TRAVIS_BUILD_DIR/build/generate_bintray.py" "$TRAVIS_BUILD_DIR"
  - cd "$TRAVIS_BUILD_DIR/build" && zip -r output "./plugins" && cd -

deploy:
  provider: bintray
  file: "$TRAVIS_BUILD_DIR/.bintray.json"
  user: "groterik"
  key:
    secure: "TOjXZ2Zk1k/eOyLbXJBXSjJ6YGu2Fz0VRTxaMCl6csIoggazgxRXf7vjax2Do1XQwwX1dnwJJwAKLSoI9Zm7dxVQLnTstFkcvY7lrEyYimPd1MQSVeUJ/5DHMoSG+JgxX6ht9tU+WpzMNwsEsAOVQxcTWTi63UFNtDw+xGU89Zc="

