#ifndef DUBPROJECTMANAGER_GLOBAL_H
#define DUBPROJECTMANAGER_GLOBAL_H

#include <QtGlobal>

#if defined(DUBPROJECTMANAGER_LIBRARY)
#  define DUBPROJECTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DUBPROJECTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DUBPROJECTMANAGER_GLOBAL_H

